#!/bin/bash
for entry in test1/*.gem
do
	java -jar GemC.jar $1 > $entry.java $entry
  	./gem $entry > $entry.out
  	diff --brief <(sort $entry.out) <(sort $entry.test) >/dev/null
	comp_value=$?

	if [ $comp_value -eq 1 ]
	then
    	echo "error in $entry"
	else
    	echo "$entry passed the test"
    fi
done