#!/bin/bash
read -p "Welcome to GEM testing! Do you want to test individual file? filename or press enter directly. " yn
if [ -n "$yn" ]; then
	subdir="SystemTests/testType/"
	dir1=$subdir$yn
	java -jar ./GemC.jar $dir1 > $dir1.java
	./Artistic/bin/astyle -n -q $dir1.java 
    ./gemc $dir1 2> $dir1.out
    diff --brief <(sort $dir1.out) <(sort $dir1.test) >/dev/null
	comp_value=$?

	if [ $comp_value -eq 1 ]
	then
    	echo "error in $yn"
	else
    	echo "$yn passed the test"
    fi

else
    for entry in SystemTests/testType/*.gem
	do
		java -jar ./GemC.jar $entry > $entry.java
		./Artistic/bin/astyle -n -q $entry.java  
  		./gemc $entry 2> $entry.out
  		diff --brief <(sort $entry.out) <(sort $entry.test) >/dev/null
		comp_value=$?

		if [ $comp_value -eq 1 ]
		then
    		echo "error in $entry"
		else
    		echo "$entry passed the test"
    	fi
	done
fi